### ISSUE TITLE
[QA]: change templates to yaml-files

### ISSUE THREAD

**Issue by kitsudaiki** [kitsudaiki/ainari#206]
### Description

At the moment the cluster-templates are looking like this for example:

```
version: 1
settings:
    max_synapse_sections: 1000

bricks:
    1,1,1
        input: test_input
        number_of_neurons: 20
    2,1,1
        number_of_neurons: 10
    3,1,1
        output: test_output
        number_of_neurons: 5
```

Originally there were 2 different types of templates and some other changes planed. At first I thought it would be a good idea to define a custom format to have more freedom. After reducing the complexity there is nothing at the moment to move from the custom format to normal yaml-files.

### Acceptance Criteria

1. The current templates are moved to a yaml-file format
2. The cluster-parser was replaced by a yaml-parser library, which also can be a third-party library
3. The internal representation of the parsed data is still the same like before
4. The SDK-API-Test was updated
5. The example within the dashboard-documenation was updated
